# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b9cdcdc80fe2ca4aebf3f1c4315e2e374d465670906d82800841cb04c25dae8bcecb2e8c0d4a411aa730bd19f537d189515e0e10636950f75e84c85e9cd16c

test:
  secret_key_base: 15bd97b78e491da8155debcf5326fab66db52e21a91ecf695afe4d42a5915a7fc18e9450b59dc76cb01b859ca3664f9a7749f301a854534f01e455d05bdbd26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
